### ISSUE TITLE
SVG export of Plotting page broken

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#106]
The following Error message appears when trying to export a Plot as SVG in ODMF:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/srv/odmf/schwingbach/src/odmf/webpage/plot.py", line 259, in image
    return plot_backend.to_image(plot, format)
  File "/srv/odmf/schwingbach/src/odmf/plot/draw_plotly.py", line 68, in to_image
    return fig.to_image(format=format)
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/plotly/basedatatypes.py", line 3743, in to_image
    return pio.to_image(self, *args, **kwargs)
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/plotly/io/_kaleido.py", line 103, in to_image
    return to_image_orca(
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/plotly/io/_orca.py", line 1535, in to_image
    ensure_server()
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/plotly/io/_orca.py", line 1390, in ensure_server
    validate_executable()
  File "/srv/odmf/schwingbach/venv/lib/python3.8/site-packages/plotly/io/_orca.py", line 1076, in validate_executable
    raise ValueError(
ValueError: 
The orca executable is required to export figures as static images,
but it could not be found on the system path.

Searched for executable 'orca' on the following path:
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python

**Comment by philippkraft** [comment]
Fixed by importing kaleido
