### ISSUE TITLE
Can't start odmf from cli command

### ISSUE THREAD

**Issue by cpwnd** [jlu-ilr-hydro/odmf#92]
After having cloned the most recent git sources (from master) and installed a new virtual env with python3.8.10, the call to the odmf cli gives me the following error.
```
$ pip install -e .
$ odmf --help
Traceback (most recent call last):
  File "/usr/local/bin/odmf", line 33, in <module>
    sys.exit(load_entry_point('odmf==1.0', 'console_scripts', 'odmf')())
  File "/usr/local/bin/odmf", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata-2.0.0-py3.6.egg/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata-2.0.0-py3.6.egg/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for odmf
```

Using the script `bin/start.py` works without a problem.

**Comment by philippkraft** [comment]
You are not using the venv and odmf is not installed in the venv (/usr/local/bin/odmf, should be ~/odmf/venv/bin/odmf)


~~~~~~~~~~.sh
python3.8 -m venv venv
source venv/bin/activate
pip install -e .
odmf  --help
~~~~~~~~~~~~~~~

**Comment by cpwnd** [comment]
Ok, I've missed it. I was sure venv was active. Thank you, now it works!

Am 01.06.21 um 17:21 schrieb Philipp Kraft:

**Comment by cpwnd** [comment]
Ok I'm running into two problems. I don't know if they are seperate problems.

This is the output of the start command:
```
$ odmf start
/home/chris/Code/python/odmf/config.yml not found. Create a template with "odmf configure". Using incomplete configuration
  File "/home/chris/Code/python/odmf/odmf/webpage/preferences.py", line 27, in __init__
    with open(self.filename, 'r') as f:
[01/Jun/2021:22:47:21] ENGINE Listening for SIGTERM.
[01/Jun/2021:22:47:21] ENGINE Listening for SIGHUP.
[01/Jun/2021:22:47:21] ENGINE Listening for SIGUSR1.
[01/Jun/2021:22:47:21] ENGINE Bus STARTING
[01/Jun/2021:22:47:21] ENGINE Serving on http://0.0.0.0:8080
[01/Jun/2021:22:47:21] ENGINE Bus STARTED
```
This doesn't look that bad, the server starts up and keeps running. But is the first line of the log a problem? Is a configuration file mandatory?

Because if I then curl the root at /, there is a permanent redirect. See output of the curl message:
```
$ curl -I http://localhost:8080/
HTTP/1.1 303 See Other
Content-Type: text/html;charset=utf-8
Server: CherryPy/18.6.0
Date: Tue, 01 Jun 2021 20:48:16 GMT
Location: http://localhost:8080/
Content-Length: 90
```


After this I tried to generate a configuration. And check whether this helps to successfully setup a server.
```
$ odmf configure
database name: odmfdb
database user: odmfdbuser
database password: 1234
database hostname: [127.0.0.1]: 
server port [8080]: 
Traceback (most recent call last):
  File "/home/chris/Code/python/odmf/.venv/bin/odmf", line 33, in <module>
    sys.exit(load_entry_point('odmf', 'console_scripts', 'odmf')())
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/chris/Code/python/odmf/odmf/odmf.py", line 59, in configure
    conf.to_yaml(conf_file.open('w'))
  File "/home/chris/Code/python/odmf/odmf/config.py", line 144, in to_yaml
    yaml.safe_dump(self.to_dict(), stream)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/yaml/__init__.py", line 306, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/chris/Code/python/odmf/.venv/lib/python3.8/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', <property object at 0x7f937e787130>)
```

So (1) from `odmf start` the server configuration seems invalid and (2) I can't generate a configuration.

**Comment by philippkraft** [comment]
And yes, to start a server you need:
1) a valid config.yml (odmf configure)
2) a working database structure (odmf make-db, odmf test-db)
